INSERT INTO PRODUCT_INFO (id, name,price,STOCK_LEVEL,STOCK_THRESHOLD_LEVEL) VALUES (1, 'Tea Glasses',15,1000,100);
INSERT INTO PRODUCT_INFO (id, name,price,STOCK_LEVEL,STOCK_THRESHOLD_LEVEL) VALUES (2, 'WIne Glasses',25,1000,100);
INSERT INTO PRODUCT_INFO (id, name,price,STOCK_LEVEL,STOCK_THRESHOLD_LEVEL) VALUES (3, 'Gift Glasses',35,1000,100);
INSERT INTO PRODUCT_INFO (id, name,price,STOCK_LEVEL,STOCK_THRESHOLD_LEVEL) VALUES (4, 'Decorative Glasses',50,1000,100);
INSERT INTO PRODUCT_INFO (id, name,price,STOCK_LEVEL,STOCK_THRESHOLD_LEVEL) VALUES (5, 'Gift Pack Bags',15,1000,100);
INSERT INTO PRODUCT_INFO (id, name,price,STOCK_LEVEL,STOCK_THRESHOLD_LEVEL) VALUES (6, '5 Grams Silver Glasses',500,100,10);

INSERT INTO SELLER_INFO (id, name,PORestriction,POLimit) VALUES (100,'Paradise Restaturent',1,10000);
INSERT INTO SELLER_INFO (id, name,PORestriction,POLimit) VALUES (101,'Apollo Health Pharmacy',1,10000);
INSERT INTO SELLER_INFO (id, name,PORestriction,POLimit) VALUES (102,'Raj Estates',1,10000);
COMMIT;